# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

repoURL: "https://github.com/redhat-ai-services/ai-accelerator-examples.git"
targetRevision: main

clusterDomainUrl: "apps.cluster.example.com"

kustomizeDirectories: []
helmDirectories: []
