apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm-modelcar-serverless

helmCharts:
- name: vllm-kserve
  releaseName: granite
  version: 0.5.11
  repo: https://redhat-ai-services.github.io/helm-charts/
  valuesFile: values.yaml
