apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "argocd-appgenerator.fullname" . }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
  - git:
      repoURL: {{ .Values.repoURL }}
      revision: {{ .Values.revision }}
      directories:
        {{- toYaml .Values.directories | nindent 8 }}
  template:
    metadata:
      name: '{{`{{path[1]}}-{{path[2]}}`}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        example: {{ include "argocd-appgenerator.fullname" . }}
    spec:
      project: {{ include "argocd-appgenerator.fullname" . }}
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            rhoai-example: models-as-a-service
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 20m
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.revision }}
        path: '{{`{{path}}`}}'
      destination:
        server: https://kubernetes.default.svc
